### ISSUE TITLE
Dextran example in documentation is broken

### ISSUE THREAD

**Issue by sleweke-bayer** [fau-advanced-separations/CADET-Process#12]
The [Dextran parameter estimation example](https://cadet-process.readthedocs.io/en/latest/examples/parameter_estimation/dextran.html) in the documentation is broken.
The file `reference_data/dextran.csv` is missing.

**Comment by schmoelder** [comment]
Hey Sam, thanks for your feedback! 

I think this is actually already fixed. It's just the documentation that hasn't been updated recently. I will work on that. 
Also note that I've been refactoring many modules of CADET-Process on the `dev` branch and I hope to make a new release in the near future. For the moment I'm not using other feature branches since too many things are developing simultaneously. This also means I regularly force-push to `dev`. If that doesn't bother you, feel free to test it. Any feedback is highly appreciated!

**Comment by mrsonne** [comment]
Hi. I just tried the examples running from `dev` and get this error `Exception: The method 'get_algorithm' has been deprecated since 0.6.0. Please use the object-oriented interface.` originating from `comparator.add_reference(reference)` in the example. I get the same problem in v0.6.3 from pypi and from `master`. Is that related to this issue or a separate one? Is there a quick-fix?  Cheers, Jacob

**Comment by schmoelder** [comment]
Hey,
I just found a solution that makes importing these kinds of examples where data is loaded from file much easier and fixes this issue. Since I'm in the process of overhauling all of the documentation, this will take a bit more time until it's published but I just wanted to give an update.

> Exception: The method 'get_algorithm' has been deprecated since 0.6.0. Please use the object-oriented interface.

This is strange. It should not be an issue any more. You simply ran the code of the example?

**Comment by schmoelder** [comment]
The example was replaced by a new example on fitting column transport parameters. It will be expanded to also include system periphery and isotherm parameters in a future release.

See: https://cadet-process.readthedocs.io/en/latest/examples/characterize_chromatographic_system/column_transport_parameters.html
