### ISSUE TITLE
Can't simulate LRMP with ncols = 1

### ISSUE THREAD

**Issue by ronald-jaepel** [fau-advanced-separations/CADET-Process#176]
setting `discretization.ncol = 1` for the LRMP 

MRE:
```python
from CADETProcess.processModel import ComponentSystem, Linear,  LumpedRateModelWithoutPores, FlowSheet, Process
from CADETProcess.simulator import Cadet

component_system = ComponentSystem(1)

binding_model = Linear(component_system, name="linear")
binding_model.is_kinetic = True
binding_model.adsorption_rate = [2]
binding_model.desorption_rate = [1]

reactor = LumpedRateModelWithoutPores(component_system, name="reactor")
reactor.binding_model = binding_model

reactor.c = [1]
reactor.q = [0]
reactor.total_porosity = 0.5
reactor.length = 1e-1
reactor.diameter = 1e-2
reactor.axial_dispersion = 1e-20
reactor.discretization.ncol = 1

reactor.solution_recorder.write_solution_bulk = True
reactor.solution_recorder.write_solution_solid = True

flow_sheet = FlowSheet(component_system)

flow_sheet.add_unit(reactor)

process = Process(flow_sheet, 'process')
process.cycle_time = 10

simulator = Cadet()
sim_results = simulator.run(process)
```

gives this error:
```python-traceback
Traceback (most recent call last):
  File "C:\Users\ronal\PycharmProjects\CADET-Process\CADETProcess\dataStructure\parameter.py", line 1194, in _prepare
    self.check_size(instance, np.array(value))
  File "C:\Users\ronal\PycharmProjects\CADET-Process\CADETProcess\dataStructure\parameter.py", line 1035, in check_size
    raise ValueError(f"Expected size {expected_size}")
ValueError: Expected size (11, 1)
```

And I can't figure it out.

**Comment by schmoelder** [comment]
The problem comes from this line (or a similar one):

https://github.com/fau-advanced-separations/CADET-Process/blob/master/CADETProcess/solution.py#L741

There used to be some inconsistencies in CADET-Core regarding singleton dimensions. I.e. the solution array was not correctly squashed and coordinates of singleton dimensions were written out. I believe, many of those issues were fixed when adding the C-API, so theoretically we could remove those lines, but this seems to cause other issues. So there is some more work to be done. :frowning_face: 

Since a single axial cell is an edge case for column models, I hope this does not affect too many people.

To address this, we should first fix the inconsistencies between CLI / C-API mentioned by @ronald-jaepel (could you please open an issue and link it here?). Moreover, we should add tests for single-component simulations.

**Comment by ronald-jaepel** [comment]
Opened the PR that adds the necessary tests here https://github.com/cadet/CADET-Python/pull/30 .
