### ISSUE TITLE
Computation time increased ~100 times in v0.8 for 20 columns SMB system

### ISSUE THREAD

**Issue by dion-is** [fau-advanced-separations/CADET-Process#75]
After upgrading to v0.8 calculation time for 20 columns carousel system increased from 5  min to 10 hours. The case is attached.

[test_20_columns.zip](https://github.com/fau-advanced-separations/CADET-Process/files/13527371/test_20_columns.zip)

**Comment by dion-is** [comment]
@schmoelder , yes,  this is just the time for pre-processing. 

I believe it is not related to solving flow rates, I'm using my own function to do it. I ran a profiler and it spends most of the time in event sorting.

**Comment by schmoelder** [comment]
We created a PR (#77) where we're trying out some things to improve this. On my local machine, your code now runs in 95 s. This is still not great since the simulation itself only takes 5 s to run but I hope it makes it at least usable again.

Note that this is still mostly untested so I hope this does not break anything. Please also let us know if you have further ideas on how to improve this situation while also keeping the flexibility that CADET-Process generally provides.
